CREATE DATABASE FORMULARIODB;

USE FORMULARIODB;

CREATE TABLE USUARIO(
  ID INT(12) PRIMARY KEY AUTO_INCREMENT,
  NOMBRE VARCHAR(255) NOT NULL,
  APELLIDO NUMERIC(12,2) NOT NULL,
  SEXO VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  TELEFONO VARCHAR(255) NOT NULL,
  DIRECCION VARCHAR(255) NOT NULL

);

